apiVersion: batch/v1
kind: Job
metadata:
    name: date-echo
spec:
    template:
        metadata:
            name: date-echo
        spec:
            containers:
                - name: date-echo
                  image: kurron/date-echo:latest
            restartPolicy: Never
